In [1]:
import pandas as pd
df=pd.read_csv("weather_data.csv")
df

         Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad             28          60     Sunny
1  02-01-2025    Vijayawada             29          62     Sunny
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy
4  05-01-2025      Banglore             32          57     Rainy
5  06-01-2025        Mumbai             33          59     Rainy
6  07-01-2025       Chennai             34          61     Sunny
7  08-01-2025    Rajamundry             32          63    Cloudy
8  09-01-2025         Eluru             31          64     Rainy
9  10-01-2025    Anakapalli             29          62     Sunny

In [2]:
df.head(3)

         Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad             28          60     Sunny
1  02-01-2025    Vijayawada             29          62     Sunny
2  03-01-2025  Viskhapatnam             30          58    Cloudy

In [3]:
df.tail(4)

         Date        City  Temperature_C  Humidity_% Condition
6  07-01-2025     Chennai             34          61     Sunny
7  08-01-2025  Rajamundry             32          63    Cloudy
8  09-01-2025       Eluru             31          64     Rainy
9  10-01-2025  Anakapalli             29          62     Sunny

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           10 non-null     object
 1   City           10 non-null     object
 2   Temperature_C  10 non-null     int64
 3   Humidity_%     10 non-null     int64
 4   Condition      10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [5]:
df.shape

(10, 5)

In [6]:
df[2:4]

         Date          City  Temperature_C  Humidity_% Condition
2  03-01-2025  Viskhapatnam             30          58    Cloudy
3  04-01-2025      Kakinada             31          55    Cloudy

In [7]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'Condition'], dtype='object')

In [8]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
df.dtypes

Date             object
City             object
Temperature_C     int64
Humidity_%        int64
Condition        object
dtype: object

In [10]:
df.Date

0    01-01-2025
1    02-01-2025
2    03-01-2025
3    04-01-2025
4    05-01-2025
5    06-01-2025
6    07-01-2025
7    08-01-2025
8    09-01-2025
9    10-01-2025
Name: Date, dtype: object

In [11]:
df[['Date','Condition']]

         Date Condition
0  01-01-2025     Sunny
1  02-01-2025     Sunny
2  03-01-2025    Cloudy
3  04-01-2025    Cloudy
4  05-01-2025     Rainy
5  06-01-2025     Rainy
6  07-01-2025     Sunny
7  08-01-2025    Cloudy
8  09-01-2025     Rainy
9  10-01-2025     Sunny

In [12]:
df['Date'][df['Condition']=='Rainy']

4    05-01-2025
5    06-01-2025
8    09-01-2025
Name: Date, dtype: object

## Reading Data

In [13]:
df=pd.DataFrame({
    "Name":["Raju","Vamsi","Navadeep"],
    "Age":[21,25,21]
})
df

       Name  Age
0      Raju   21
1     Vamsi   25
2  Navadeep   21

In [14]:
df.head(2)

    Name  Age
0   Raju   21
1  Vamsi   25

In [15]:
df.tail(1)

       Name  Age
2  Navadeep   21

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [17]:
df.shape

(3, 2)

In [18]:
df[1:2]

    Name  Age
1  Vamsi   25

In [19]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [21]:
df.dtypes

Name    object
Age      int64
dtype: object

In [22]:
df.Name

0        Raju
1       Vamsi
2    Navadeep
Name: Name, dtype: object

In [23]:
df[['Name','Age']]

       Name  Age
0      Raju   21
1     Vamsi   25
2  Navadeep   21